### ISSUE TITLE
When do you plan to release the code ?

### ISSUE THREAD

**Issue by Neuronys** [CZWin32768/XNLG#1]
Congratulations for your paper. 
I'm french and it's not easy to find cross-lingal model that work for question generation. 
I hope you will release your code soon.
Cheers 
Philippe

**Comment by CZWin32768** [comment]
Thanks for your interest in our work. We have released the code and dataset. 

Please free to contact me if you have any questions.

**Comment by Neuronys** [comment]
Thanks a lot
Is your work related to UniLM ? I've noticed there are some names in common between the 2 papers
