### ISSUE TITLE
Multi-GPU Fine tuning

### ISSUE THREAD

**Issue by dakshvar22** [CZWin32768/XNLG#14]
I want to fine-tune the pre-trained model on a custom task which is very similar to the XSumm task. The dataset for fine-tuning is quite large and hence I would like to use a multi-gpu setup. However, I noticed that the initial slurp related code for facilitating distributed data parallelism which is used in `xnlg-train.py` does not exist for `xnlg-ft.py`. Even the [README for fine-tuning](https://github.com/CZWin32768/XNLG#training-for-zero-shot-as) does not suggest invoking the script with `python -m torch.distributed.launch` as it is the case with `xnlg-train.py`.
So, I had my doubts of whether the fine-tuning is currently possible to be distributed or not and hence I added a few changes - 
Firstly, I added the following two function calls right at the beginning of fine-tuning code, specifically at the beginning of `run_xnlg` function inside `xnlg-ft.py` - 

```
    # initialize the multi-GPU / multi-node training
    init_distributed_mode(params)

    # initialize SLURM signal handler for time limit / pre-emption
    init_signal_handler()
```

Secondly, I changed the call to `torch.load` on line 256 of `xnlg-ft.py` to load the model based on `params.local_rank`.
```
reloaded = torch.load(params.model_path, map_location=lambda storage, loc: storage.cuda(params.local_rank))['model']
```
Thirdly, I invoke the script with `python -m torch.distributed.launch`.

Now, this ensures that multiple processes are spawned(one for each GPU available) but there might be a deeper issue of data parallelism. My suspicion is that right now, each batch is passed to each model replica on each GPU, whereas the ideal scenario should be that there should be no overlap in batches passed to each GPU. I see that for pre-training this is done in `load_para_data` and `load_mono_data` functions in `loader.py`.
Can you please confirm that this is indeed an issue with the fine-tuning code?

**Comment by CZWin32768** [comment]
The finetuning code doesn't support multi-GPU finetuning. Directly running it with DDP launcher can cause the problem that same batches are passed to GPUs.

If you want to finetune in the DDP mode, I suggest using a `DistributedSampler` to fix this issue.
