### ISSUE TITLE
Possible bug in MT step

### ISSUE THREAD

**Issue by dakshvar22** [CZWin32768/XNLG#15]
Hi,

Shouldn't the `x` parameter [here](https://github.com/CZWin32768/XNLG/blob/master/xnlg/src/trainer.py#L856) in the call to `self.decoder` be set to `x1` instead of `x2`? The decoder should be conditioned only on the input and not the target sentence right?

Can you please clarify this?

**Comment by CZWin32768** [comment]
y_n is predicted by p(y_n | y_<n, x). 

During training, y_<n is the ground truth data. In evaluation, y is only conditioned on x, and y_<n is generated by the decoder.
