### ISSUE TITLE
InfoXLM pretrained model ?

### ISSUE THREAD

**Issue by Neuronys** [CZWin32768/XNLG#16]
Hello
Thanks for sharing your interesting paper on InfoXLM.
Where can I find the pretrained model and some information to finetune it for the French language ?
Thanks in advance

**Comment by CZWin32768** [comment]
Thanks for your  interest. Also, my apologies for the slow reply. I have uploaded the pretrained InfoXLM / [XLM-Align](https://github.com/CZWin32768/XLM-Align) models to huggingface. Model links: ([InfoXLM-base](https://huggingface.co/microsoft/infoxlm-base), [InfoXLM-large](https://huggingface.co/microsoft/infoxlm-large), [XLM-Align-base](https://huggingface.co/microsoft/xlm-align-base))

For the pretraining code, I have just created a new PR [here](https://github.com/microsoft/unilm/pull/377). So, you can find the pretraining code at [this page](https://github.com/microsoft/unilm/tree/master/infoxlm) soon.
