### ISSUE TITLE
is it related to UniLM ?

### ISSUE THREAD

**Issue by Neuronys** [CZWin32768/XNLG#2]
Hi
I've notice some name in common between the 2 papers (https://arxiv.org/pdf/1905.03197.pdf and https://arxiv.org/pdf/1909.10481v3.pdf). How these 2 projects are related ?
Thanks and congrats for such an impressive work !
Philippe

**Comment by CZWin32768** [comment]
Both XNLG and UniLM are pre-trained models for NLG tasks. UniLM is designed for monolingual NLG, while XNLG focuses on transferring NLG supervision signals from a language to another language. For example, fine-tuned with English abstractive summarization data, XNLG can directly perform summarization on French data.
