### ISSUE TITLE
decoding vocabulary for other languages

### ISSUE THREAD

**Issue by jian-mo** [CZWin32768/XNLG#4]
Hi,
Thanks very much for the great work. I have tried question generation with the provided Chinese vocabulary and have successful results. 
I'd like to experiment with the decoding of other languages say, French. 
Could you elaborate on where or how to get/generate such a vocabulary file just like the[ Chinese one](https://drive.google.com/file/d/1jc7osl6XG7Cp3js5ui68idRlSYKzTwHT)?

Thanks

**Comment by CZWin32768** [comment]
Just generate a decoding vocabulary through the word count of your corpus (in French). It would be better if the corpus and your input sentences belong to the same domain.

**Comment by jian-mo** [comment]
thanks for the reply, I have generated the vocab needed
