### ISSUE TITLE
the vocabulary if decode_with_vocab is true

### ISSUE THREAD

**Issue by Saner3** [CZWin32768/XNLG#9]
Hi @CZWin32768 , if params.decode_with_vocab is set to true, then during decoding of  the inference/generate phase, the model will restricted to the vocabulary we provided. And I am a little confused about where this vocabulary come from? is this the vocabulary of the test.q.zh/en set? How can I provide my own vocabulary if I am using my own dataset? And can we also use a similar vocab in the training phase?

**Comment by CZWin32768** [comment]
As written in our paper: "During decoding Chinese, we utilize a subset of vocabulary, which is obtained
from the passage sentences of the WebQA dataset."

For each language, you should generate a vocabulary file with lines of tokens, such as:
```
token_A\t1
token_B\t1
...
```
